---
- include_tasks: validate.yml
  tags: [ always, validate ]

- include_tasks: vpc.yml
  tags: [ vpc ]

- include_tasks: subnets.yml
  tags: [ subnets ]

- include_tasks: vpg.yml
  tags: [ vpg ]

- include_tasks: igw.yml
  tags: [ igw ]

- include_tasks: nat.yml
  tags: [ nat ]

- include_tasks: tgw_attach.yml
  tags: [ tgw ]
  vars:
    ansible_connection: local

- include_tasks: routes.yml
  tags: [ routes ]

- include_tasks: security.yml
  tags: [ security ]
