---

#
# This set of tasks exist to work around an open Ansible issue:
#
# see: # see https://github.com/ansible/ansible/issues/55823
#

- debug:
    msg: "VPC id is: {{ aws_vpc_id }}"
    verbosity: 1

- debug:
    msg: "TGW ID is: {{ aws_vpc_transit_gateway_id }}"
    verbosity: 1

- debug:
    msg: "Public subnet ID is: {{ aws_vpc_public_subnet_id }}"
    verbosity: 1

# For manual testing
# - pause:
#     prompt: "Continue to attach the tgw..."

- name: SHELL | attach tgw to vpc via AWS CLI
  shell: |
    aws ec2 create-transit-gateway-vpc-attachment \
    --transit-gateway-id {{ aws_vpc_transit_gateway_id }} \
    --vpc-id {{ aws_vpc_id }} \
    --subnet-id {{ aws_vpc_public_subnet_id }} \
    --options DnsSupport=enable,Ipv6Support=disable \
    --tag-specifications 'ResourceType=transit-gateway-attachment,Tags=[{Key=Name,Value={{ aws_vpc_name }}_tgw_attachment}]'
  register: task_result

- debug:
    var: task_result
    verbosity: 1

#
# This is trippy AF, but start our recursive wait
#
- name: SET_FACT | init loop counter to 0
  set_fact:
    aws_vpc_txgw_loop_ctr: 0

- include_tasks: tgw_attach_wait.yml

#
# If/when we get here, the VPC is attached to the transit gateway
#

# For manual testing
# - pause:
#     prompt: "Continue to proceed post tgw attach"
