---

- name: Ensure Virtual Private Cloud (VPC) absent
  ec2_vpc_net:
    aws_access_key: "{{ aws_vpc_aws_access_key }}"
    aws_secret_key: "{{ aws_vpc_aws_secret_key }}"
    state: absent
    name: "{{ aws_vpc_name + '_vpc' }}"
    cidr_block: "{{ aws_vpc_cidr_block }}"
